version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=8556
    volumes:
      - /home/kasm/datav1:/opt
      - /home/kasm/profiles:/profiles #optional
    ports:
      - 3000:3000
    expose:
      - 8556
    restart: unless-stopped
