version: "2.1"
services:
  kasm:
    image: lscr.io/linuxserver/kasm:latest
    container_name: kasm
    privileged: true
    environment:
      - KASM_PORT=8556
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - /home/kasm/datav1:/opt
      - /home/kasm/profiles:/profiles #optional
    ports:
      - 8331:3000
    expose:
      - 8556
    restart: unless-stopped
