version: '3'

services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - "9443:9443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.clgvjga5e001pn6ag33bc1oot-portainer.rule=Host(`portainer.devopportunities.dev`)" # Replace with your domain name
      - 'traefik.http.routers.clgvjga5e001pn6ag33bc1oot-portainer.entrypoints=websecure'
      - "traefik.http.services.clgvjga5e001pn6ag33bc1oot-portainer.loadbalancer.server.port=9443"
      - "traefik.docker.network=coolify-proxy" # Replace with your Traefik network name

volumes:
  portainer_data:

networks:
  coolify-proxy: # Define your external Traefik network
    external:
      name: coolify-proxy